apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
spec:
  restartPolicy: Never
  replicas: 1
  selector:
    name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: hello
        image: hello-world:latest
