apiVersion: v1
kind: ReplicationController
spec: 
  replicas: 2
  selector:
    name: redis
  template:
    metadata:
      labels: 
        name: redis
    spec:
      containers:
        -name: redis
         image: kubernetes/redis:v1
